### ISSUE TITLE
Problem flashing C.H.I.P. pro

### ISSUE THREAD

**Issue by SCordibella** [myfreescalewebpage/meta-chip#2]
Hi, I am trying to use your meta layer in order to build a chip pro release...
When I try to flash my image to the board (dev kit 1.0) I have the following error:

BUILDROOT_OUTPUT_DIR = ..
== preparing images ==
PADDED_SPL_SIZE=0x000000c4
0+1 records in
1+0 records out
4194304 bytes (4,2 MB, 4,0 MiB) copied, 0,00673643 s, 623 MB/s
UBOOT_SIZE=0x00400000
PADDED_UBOOT_SIZE=0x400000
0+0 records in
0+0 records out
0 bytes copied, 0,000147694 s, 0,0 kB/s
echo Configuring Video Mode
reset
Image Name:   flash CHIP
Created:      Wed Mar 29 17:45:27 2017
Image Type:   ARM Linux Script (uncompressed)
Data Size:    1022 Bytes = 1.00 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 1014 Bytes = 0.99 kB = 0.00 MB
== upload the SPL to SRAM and execute it ==
waiting for fel.............OK
== upload spl ==
== upload u-boot ==
== upload u-boot script ==
== upload ubi ==
100% [============================================================] 
== execute the main u-boot binary ==
== write ubi ==
flashing.......................................................................................................TIMEOUT
ERROR: could not flash:

Any help will be appreciated.
Stefano.

**Comment by myfreescalewebpage** [comment]
Hi @JubaHub 
Thanks for this report, I ave just received my CHIP pro dev kit, but not yet tried to load it.
I will try to check this issue soon, but if you find any solution before, thanks for sharing :-)
Joel

**Comment by myfreescalewebpage** [comment]
Support of C.H.I.P. PRO finally added after few months not available to work on this subject :-) The examples of my meta layer https://github.com/myfreescalewebpage/meta-chip-examples have also been updated and all are working with both C.H.I.P. and C.H.I.P. PRO boards.
All have been reworked: u-boot, kernel, etc.
Important note: my chip tools have also been completely reworked: https://github.com/myfreescalewebpage/chip-tools.

@junahub, you can test it, if not too late for you of course :-)

Closing the issue.

**Comment by SCordibella** [comment]
Hi, unfortunately I am not using the CHI Pro right now.
I hope to start working again on that but not in the next month.

I worked with @texierp on this layer https://github.com/texierp/meta-chip .
It could be a good comparison point.

Thank you for your effort,
Stefano.

**Comment by myfreescalewebpage** [comment]
I have tried texiep meta-layer too, but not successfully build here.
However, in any case, we have not the same philosophy, that's good to see different solutions :-)
Joel

**Comment by texierp** [comment]
Hi @myfreescalewebpage,

Thanks for your feeback :)
Which branch did you test for your build ?

Thanks

PJ

PS: great job for your layers ;)

**Comment by myfreescalewebpage** [comment]
Hi @texierp 
Used repo as described in your readme so branches selected by the default.xml file.
What is the distro used on your host ?
Thanks, what was motivating is the *$!!*$/*$** scripts and setup provided by NTC to load the boards. I prefer not to "hide" this kind of parts to the developers, I think they must be clear (a reason for which I'm not using repo also!)
I'm currently working on the integration of xenomai based on my layer :-) A little bit hard because nobody seems to have port xenomai on kernel 4.4 on this arch....
Joel
